### ISSUE TITLE
Creates invalid changelog files if release notes are not 3x#

### ISSUE THREAD

**Issue by olivernybroe** [stefanzweifel/php-changelog-updater#22]
When using this plugin together with github's auto changelog generator, it ends up creating invalid changelog, as GitHub by default uses a h2, not a h3 for their headers. 

Taking a look at Laravel Health from Spatie, we can see here how the changelog file is invalid, making tools unable to read it correctly.
https://github.com/spatie/laravel-health/blob/main/CHANGELOG.md

It would be cool if the plugin could change the headers to the right one, so it can be used together with githubs auto changelog feature 👍

**Comment by stefanzweifel** [comment]
👍 

Something I've noticed in my own CHANGELOGs too. Would be cool if we could shift the incoming Markdown headings.

**Comment by olivernybroe** [comment]
Yep, I guess the main problem here is that this should only happen if a h2 heading is found. 
Because if you only have h3 headings, then that's fine. 🤔 


To increase them all with one `#`, we could do something like this.
```
$result = preg_replace('/^(#+)/m', '#$1', $changelog);
```

**Comment by stefanzweifel** [comment]
As the CLI parses the incoming markdown to an AST, I wonder if we could magically "fix" the AST.

- only 1 `h1` ("Changelog")
- headings for releases or "Unreleased" heading are `h2`
- headings in the incoming markdown release notes are "shifted" to fit under `h2` but still keep their own hierarchy

I have a busy week ahead, but sounds like a fun problem to solve. Would be cool to ship this in the upcoming weeks.

**Comment by stefanzweifel** [comment]
I've prepared a fix for this in #24.

The CLI will automatically shift all h1 and h2 headings to be h3 headings. But it doesn't keep hierarchy. Meaning if you have the following markdown …

```md
# Added

## package-a

## package-b
```

it won't be translated into this markdown …


```md
### Added

#### package-a

#### package -b
```

but instead into this …



```md
### Added

### package-a

### package-b
```

The PR as is would fix the problem you mentioned and would work great with GitHub's auto generated release notes.

I think not keeping hierarchy is a pill we could swallow right now and fix in a later release (Turns out that's actually not that easy to solve; or maybe I'm just seeing a simple solution right now.)
I also assume that the majority of users use the auto generated release notes and if not, already take care of passing release notes with the right hierarchy of headings to the Action/CLI.

@olivernybroe What are you thoughts on this?

**Comment by olivernybroe** [comment]
@stefanzweifel Yeah that was the same hurdle I saw when looking at it. 

I think this is good enough for first edition of a fix for it. It at least does so people don't end up with invalid release note documents 👍 

Great job 😄

**Comment by stefanzweifel** [comment]
Just tagged `v1.6.0` of the CLI which contains this improvement: https://github.com/stefanzweifel/php-changelog-updater/releases/tag/v1.6.0

Will release an update of the Action shortly.
